version: '3.1'
services:
  filmorate-server:
    build: .
    image: filmorate
    container_name: filmorate
    ports:
      - "8080:8080"
    depends_on:
      - filmorate-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://filmorate-db:5432/filmorate
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  filmorate-db:
    image: postgres:14-alpine
    container_name: filmorate-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=filmorate
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root