CREATE TABLE IF NOT EXISTS filmorate_users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL,
  login varchar NOT NULL,
  name varchar,
  birthday date,
  CONSTRAINT UC_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS mpa (
  mpa_id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mpa varchar
);

CREATE TABLE IF NOT EXISTS genre (
  genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre varchar
);

CREATE TABLE IF NOT EXISTS films (
  film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL,
  description varchar,
  release_date date,
  duration integer,
  rating Integer REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS likes (
  film_id integer REFERENCES films (film_id),
  user_id integer REFERENCES filmorate_users (user_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
  film_id integer REFERENCES films (film_id),
  genre_id integer REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS friends (
  user1_id integer,
  user2_id integer,
  confirmed Boolean DEFAULT false,
  CONSTRAINT not_self_friend CHECK (user1_id != user2_id)
);

