CREATE TABLE filmorate_users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(50) NOT NULL,
  login varchar(50) NOT NULL,
  name varchar(50),
  birthday date
);

ALTER TABLE filmorate_users ADD CONSTRAINT UC_email UNIQUE (email);

ALTER TABLE filmorate_users ADD CONSTRAINT UC_login UNIQUE (login);