CREATE TABLE review_event
(
    timestamp timestamp,
    user_id integer REFERENCES filmorate_users (user_id) ON DELETE CASCADE,
    eventType ENUM ('LIKE', 'REVIEW', 'FRIEND') DEFAULT 'REVIEW',
    operation ENUM ('REMOVE', 'ADD', 'UPDATE'),
    review_event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id integer REFERENCES reviews (review_id) ON DELETE CASCADE
);