CREATE TABLE friend_event
(
    timestamp timestamp,
    user_id integer REFERENCES filmorate_users (user_id) ON DELETE CASCADE,
    eventType ENUM ('LIKE', 'REVIEW', 'FRIEND') DEFAULT 'FRIEND',
    operation ENUM ('REMOVE', 'ADD', 'UPDATE'),
    friend_event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friendship_id integer REFERENCES friends (friendship_id) ON DELETE CASCADE
);