CREATE TABLE filmorate_users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL,
  login varchar NOT NULL,
  name varchar,
  birthday date
);

ALTER TABLE filmorate_users ADD CONSTRAINT UC_email UNIQUE (email);

ALTER TABLE filmorate_users ADD CONSTRAINT UC_login UNIQUE (login);