CREATE TABLE films
(
    film_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50) UNIQUE NOT NULL,
    description  varchar(255),
    release_date date               NOT NULL,
    duration     integer,
    mpa_id       integer REFERENCES mpa (mpa_id)
);