CREATE TABLE films (
  film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL,
  description varchar,
  release_date date NOT NULL,
  duration integer,
  rating Integer REFERENCES mpa (mpa_id)
);