CREATE TABLE films (
  film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) UNIQUE NOT NULL,
  description varchar(255),
  release_date date NOT NULL,
  duration integer,
  rating integer REFERENCES mpa (mpa_id)
  CONSTRAINT check_dates CHECK (release_date > '1895-12-28')
);