CREATE TABLE like_event
(
    timestamp timestamp,
    user_id integer REFERENCES filmorate_users (user_id) ON DELETE CASCADE,
    eventType ENUM ('LIKE', 'REVIEW', 'FRIEND'),
    operation ENUM ('REMOVE', 'ADD', 'UPDATE'),
    like_event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    like_id integer REFERENCES likes (like_id) ON DELETE CASCADE
);