CREATE TABLE like_event
(
    timestamp timestamp DEFAULT NOW(),
    user_id integer REFERENCES filmorate_users (user_id) ON DELETE CASCADE,
    eventType ENUM ('LIKE', 'REVIEW', 'FRIEND'),
    operation ENUM ('REMOVE', 'ADD', 'UPDATE'),
    event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id integer REFERENCES films (film_id) ON DELETE CASCADE
);